# === comfyui-hunyuan : HunyuanVideo 1.5 720p t2v — endpoint dedie ===
# Licence Tencent (verifier seuil commercial).
FROM runpod/worker-comfyui:5.8.6-base
RUN wget -q -O /comfyui/models/diffusion_models/hunyuanvideo1.5_720p_t2v_fp16.safetensors \
    "https://huggingface.co/Comfy-Org/HunyuanVideo_1.5_repackaged/resolve/main/split_files/diffusion_models/hunyuanvideo1.5_720p_t2v_fp16.safetensors"
RUN wget -q -O /comfyui/models/text_encoders/qwen_2.5_vl_7b_fp8_scaled.safetensors \
    "https://huggingface.co/Comfy-Org/HunyuanVideo_1.5_repackaged/resolve/main/split_files/text_encoders/qwen_2.5_vl_7b_fp8_scaled.safetensors"
RUN wget -q -O /comfyui/models/text_encoders/byt5_small_glyphxl_fp16.safetensors \
    "https://huggingface.co/Comfy-Org/HunyuanVideo_1.5_repackaged/resolve/main/split_files/text_encoders/byt5_small_glyphxl_fp16.safetensors"
RUN wget -q -O /comfyui/models/vae/hunyuanvideo15_vae_fp16.safetensors \
    "https://huggingface.co/Comfy-Org/HunyuanVideo_1.5_repackaged/resolve/main/split_files/vae/hunyuanvideo15_vae_fp16.safetensors"
